// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TwitchFighter.API.Data;

#nullable disable

namespace TwitchFighter.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110215459_AddHeroSkinToUser")]
    partial class AddHeroSkinToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TwitchFighter.API.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hint")
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "first_kill",
                            Description = "Defeat your first monster",
                            Hint = "Defeat a monster",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "First Blood"
                        },
                        new
                        {
                            Id = 2,
                            Code = "wave_10",
                            Description = "Reach wave 10",
                            Hint = "Keep fighting!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Getting Started"
                        },
                        new
                        {
                            Id = 3,
                            Code = "wave_50",
                            Description = "Reach wave 50",
                            Hint = "Half way there!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Veteran"
                        },
                        new
                        {
                            Id = 4,
                            Code = "wave_100",
                            Description = "Reach wave 100",
                            Hint = "The century awaits!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Centurion"
                        },
                        new
                        {
                            Id = 5,
                            Code = "first_sub",
                            Description = "Receive your first subscription",
                            Hint = "Get a subscriber",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Community Support"
                        },
                        new
                        {
                            Id = 6,
                            Code = "crit_master",
                            Description = "Reach 50% critical chance",
                            Hint = "Followers boost crit!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Critical Master"
                        },
                        new
                        {
                            Id = 7,
                            Code = "speed_demon",
                            Description = "Reach 5.0 attack speed",
                            Hint = "Subs boost speed!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Speed Demon"
                        },
                        new
                        {
                            Id = 8,
                            Code = "whale",
                            Description = "Receive 10,000 bits total",
                            Hint = "Bits add up!",
                            IconPath = "/cheevos/first_kill.png",
                            Name = "Whale Watcher"
                        });
                });

            modelBuilder.Entity("TwitchFighter.API.Models.Progress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BestWave")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentMonth")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentWave")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Progresses");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.Stats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Atk")
                        .HasColumnType("integer");

                    b.Property<int>("CritChance")
                        .HasColumnType("integer");

                    b.Property<int>("CritDamage")
                        .HasColumnType("integer");

                    b.Property<int>("MonthBits")
                        .HasColumnType("integer");

                    b.Property<decimal>("MonthDonations")
                        .HasColumnType("numeric");

                    b.Property<int>("MonthFollows")
                        .HasColumnType("integer");

                    b.Property<int>("MonthSubs")
                        .HasColumnType("integer");

                    b.Property<decimal>("Spd")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalBits")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalDonations")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalFollows")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSubs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("HeroSkin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LayoutMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<bool>("ShowDamageNumbers")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHUD")
                        .HasColumnType("boolean");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.UserAchievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AchievementId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AchievementId");

                    b.HasIndex("UserId", "AchievementId")
                        .IsUnique();

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.Progress", b =>
                {
                    b.HasOne("TwitchFighter.API.Models.User", "User")
                        .WithOne("Progress")
                        .HasForeignKey("TwitchFighter.API.Models.Progress", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.Stats", b =>
                {
                    b.HasOne("TwitchFighter.API.Models.User", "User")
                        .WithOne("Stats")
                        .HasForeignKey("TwitchFighter.API.Models.Stats", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.UserAchievement", b =>
                {
                    b.HasOne("TwitchFighter.API.Models.Achievement", "Achievement")
                        .WithMany("UserAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TwitchFighter.API.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.Achievement", b =>
                {
                    b.Navigation("UserAchievements");
                });

            modelBuilder.Entity("TwitchFighter.API.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Progress");

                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
